# Generated by Django 4.2.4 on 2023-08-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='TgService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=32, verbose_name='Телеграм ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Телеграм ID',
                'verbose_name_plural': 'Телеграм ID',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('delivered_time', models.DateTimeField(auto_now_add=True, verbose_name='Доставлено в')),
                ('overdue_time', models.DateTimeField(blank=True, null=True, verbose_name='Просроченное время')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Регулярный заказ',
                'verbose_name_plural': 'Регулярные заказы',
            },
        ),
    ]
