# Generated by Django 4.2.4 on 2023-08-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=1)),
                ('schedule_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['day_of_week', 'schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='TgService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=32, verbose_name='Телеграм ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Телеграм ID',
                'verbose_name_plural': 'Телеграм ID',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('delivered_time', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено в')),
                ('overdue_time', models.DurationField(blank=True, null=True, verbose_name='Просроченное время')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ для доставки',
                'verbose_name_plural': 'Заказы для доставки',
                'ordering': ['-dead_line'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик')),
                ('delivery_schedule', models.ManyToManyField(to='delivery.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Расписание заказа',
                'verbose_name_plural': 'Расписание заказов',
                'ordering': ['customer'],
            },
        ),
    ]
