# Generated by Django 4.2.4 on 2023-08-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='delivery_schedule',
            field=models.ManyToManyField(to='delivery.schedule', verbose_name='Расписание'),
        ),
    ]
