# Generated by Django 4.2.4 on 2023-08-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчика', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
