# Generated by Django 4.2.4 on 2023-08-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_order_delivered_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Monday')], max_length=1)),
                ('shedule_time', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['dead_line'], 'verbose_name': 'Регулярный заказ', 'verbose_name_plural': 'Регулярные заказы'},
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer')),
                ('delivery_shedule', models.ManyToManyField(to='delivery.schedule')),
            ],
        ),
    ]
