# Generated by Django 4.2.4 on 2023-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя получателя'),
        ),
    ]
