# Generated by Django 4.2.4 on 2023-08-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryschedule',
            options={'verbose_name': 'Расписание заказа', 'verbose_name_plural': 'Расписание заказов'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='shedule_time',
            new_name='schedule_time',
        ),
    ]
