# Generated by Django 4.2.4 on 2023-08-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-dead_line'], 'verbose_name': 'Заказ для доставки', 'verbose_name_plural': 'Заказы для доставки'},
        ),
    ]
