# Generated by Django 4.2.4 on 2023-08-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='overdue_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Просроченное время'),
        ),
    ]
